## Programming for AI Workshop 6 Activity 1

In [1]:
import plotly.express as px
import pandas as pd

In [2]:
#Read in the data file

fifa = pd.read_csv('FifaGeo.csv')

In [3]:
#Take a look at the data

fifa.head()

,PlayerId,Name,Age,Nationality,OverallRating,Potential,Club,Value,Wage,Lat,Long,Count
0,138698,A. Abdi,31,Switzerland,69,69,Sheffield Wednesday,900000,13000,64.630615,-21.683928,1
1,106231,A. Aduriz,37,Spain,82,82,Athletic Club de Bilbao,8000000,29000,40.069011,-2.138824,1
2,148684,A. Al Habsi,36,Oman,72,72,Al Hilal,425000,12000,35.309981,134.860306,1
3,138297,A. Alvarez,33,El Salvador,65,65,Houston Dynamo,325000,2000,9.534111,-13.689416,1
4,112373,A. Balijon,35,France,66,66,Le Havre AC,150000,1000,64.007376,-22.300247,1

In [4]:
#Create the scatter showing Potential matched against Age
px.scatter(fifa, 'Age', 'Potential', hover_data = ['Name','Club', 'Nationality'])

The plot does not look like the plot on the Activity sheet. What is the difference? What can be done to make it like the one on the Activity sheet?

In [5]:
t1fifa = fifa.groupby('Age').mean(numeric_only=True).reset_index()
t1fifa.head()

,Age,PlayerId,OverallRating,Potential,Value,Wage,Lat,Long,Count
0,25,146947.0,72.000000,77.000000,4.000000e+06,14000.0,60.226896,24.866373,1.0
1,26,143809.0,72.000000,74.000000,4.000000e+06,12000.0,24.255602,120.830420,1.0
2,27,144200.0,71.000000,72.000000,2.000000e+06,4000.0,26.216375,50.529847,1.0
3,28,135814.5,69.500000,69.500000,1.762500e+06,22500.0,10.126018,97.983966,1.0
4,30,141713.0,72.666667,72.666667,1.035833e+07,20000.0,29.761635,53.968667,1.0

In [6]:
#Create the scatter showing Potential matched against Age
px.scatter(t1fifa, 'Age', 'Potential', hover_data = "Wage")

Note - it does not make sense to have the  hover data about individual attributes when presenting the graph using average values per age. The hover data in the above diagram was changed to "Wage"

In [7]:
#Create the scatter showing Value matched against Age
px.scatter(fifa, 'Age', 'Value', hover_data = ['Name','Club', 'Nationality'])

In [8]:
#Create the Geomap
px.scatter_geo(fifa, fifa['Lat'], fifa['Long'], hover_data = ['Club'])

In [9]:
#Create a line plot for OverallRating of players
px.line(fifa,'Name', 'OverallRating')

The graph produced isn't quite like the plot on the activity sheet because OverallRating is not sorted.  The code below makes a graph more like the one on the activity sheet.

In [10]:
df = fifa.sort_values(by="OverallRating", ascending=False)
fig = px.line(df, x="Name", y="OverallRating")
fig.show()

Next you will create the table.  For this you have call the Table method from plotly.graph_objects library directly to create a Table in a form plotly can understand.

In [11]:
import plotly.graph_objects as go

In [12]:
table_trace = go.Table (
    header=dict(values=['Name', 'Nationality', 'OverallRating']),
    cells=dict(values=[fifa['Name'], fifa['Nationality'], fifa['OverallRating']])
)

In [13]:
tablefig = go.Figure(data=[table_trace])

In [14]:
tablefig.show()

In [15]:
#Create the Pie Chart
px.pie(fifa,'Nationality', 'Count')

The above graphic has not rendered in aesthetically pleasing way. The form can be improved by making it into a figure with the following commands.

In [16]:
piefig = px.pie(fifa,'Nationality', 'Count')

In [17]:
piefig.update_traces(textinfo='none')

How do you think the graphs here compare to the graphs created via PowerBI and shown on the image in the Activity sheet?